version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Eslint
          command: yarn lint

      - run:
          name: Tests
          command: yarn test --maxWorkers=2

workflows:
  version: 2
  test_branch:
    jobs:
      - test
